---
title: "Graphs for Amita's paper - with data from U Laval"
author: "Karen Cristine Goncalves dos Santos"
date: "`r format(Sys.time(), '%b %d %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      root.dir = "E:/amita")
library(magrittr)
library(reshape2)
library(tidyverse)
library(ggforce)


```

```{r echo=FALSE, fig.height=6, fig.width=5, message=FALSE, warning=FALSE, paged.print=FALSE}
quants <- data.frame(Test = c(
  "IFN vs Control", "NL vs Control", "VI vs Control", "VI vs IFN", "VI vs NL"),
  Identified = rep(5223, 5),
  Quantifiable = c(4562, 4573, 4629, 4664, 4611),
  Quantified = c(4321, 4325, 4366, 4393, 4356)
  )

melt_quants <- melt(quants, id = "Test")

ggplot(melt_quants, aes(Test, value, fill = variable, color = variable)) + 
  geom_col(position = "dodge2") + scale_fill_discrete(name = "") + 
  scale_color_discrete(name = "") +
  geom_text(aes(label = value, y = value - 290), 
            angle = 90, position = position_dodge(0.9), color = "black") +
  labs(x = "Test", y = "Number of proteins") +
  theme_bw() + theme(axis.text = element_text(color = "black"),
                     legend.position = "bottom")
```


```{r include=FALSE}
org.adj.pVal <- read.delim("qval_zscore_stat.txt", header = T, stringsAsFactors = F)

qval <- org.adj.pVal[, c("Accession", grep("qvalue", colnames(org.adj.pVal), value = T))]
colnames(qval) <-  gsub("_qvalue", "", colnames(qval))

zscore_ratio <- org.adj.pVal[, c("Accession", grep("ZscRatio", colnames(org.adj.pVal), value = T))]
colnames(zscore_ratio) <- gsub("_ZscRatio", "", colnames(zscore_ratio))

status <- org.adj.pVal[, c("Accession", grep("stat", colnames(org.adj.pVal), value = T))]
colnames(status) <- gsub("_statVariant", "", colnames(status))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
melt_qval <- melt(qval, id = "Accession") %>% cbind(Variable = "qValue")
melt_zscore <- melt(zscore_ratio, id = "Accession") %>% cbind(Variable = "zscore_ratio")
melt_status <- melt(status, id = "Accession") %>% cbind(Variable = "status")
colnames(melt_qval)[2] <- colnames(melt_zscore)[2] <- colnames(melt_status)[2] <- "Test"

for_plots <- data.frame(melt_qval, melt_zscore[, "value"], melt_status[, "value"])
colnames(for_plots) <- c("Accession", "Test", "qValue", "variable", "Zscore_ratio", "Status")
for_plots$variable = NULL

for_plots$Test <- as.character(for_plots$Test) %>%
  gsub(pattern = "IFN_Virus", replacement = "VI") %>%
  gsub(pattern = "Virus", replacement = "NL") %>%
  gsub(pattern = "\\.", replacement = " vs ") %>%
  factor(levels = c("IFN vs Control", "NL vs Control", "VI vs Control", 
                    "VI vs IFN", "VI vs NL"))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
Total <- Down_regulated <- Up_regulated <- c()
summary_plot <- data.frame(matrix(nrow = 0, ncol = 3))
dap <- list()
for (i in levels(for_plots$Test)) {
  a <- gsub(replacement = "IFN_Virus", pattern = "VI", x = i) %>%
    gsub(replacement = "Virus", pattern = "NL") %>%
    gsub(replacement = "\\.", pattern = " vs ") 
  
  zsc <- paste0(a, "_ZscRatio"); qv <- paste0(a, "_qvalue"); statv <- paste0(a, "_statVariant")
  
  dap[[i]] <- org.adj.pVal[ abs(org.adj.pVal[, zsc]) > 1.96 & org.adj.pVal[, statv] == "VARIANT", "Accession" ]
  
  Total <- length(dap[[i]])
  Up_regulated <- length(zscore_ratio[ zscore_ratio$Accession %in% dap[[i]] & zscore_ratio[, a] < -1.96, a])
  Down_regulated <- length(zscore_ratio[ zscore_ratio$Accession %in% dap[[i]] & zscore_ratio[, a]  > 1.96, a])
  summary_plot <- rbind(summary_plot, c(Total, Up_regulated, Down_regulated)) %>% as.data.frame()
  colnames(summary_plot) <- c("Total", "Up-regulated", "Down-regulated")

}
rownames(summary_plot) <- summary_plot$Test <- levels(for_plots$Test)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
plot_summary <- reshape2::melt(summary_plot, id = "Test")

ggplot(plot_summary, aes(Test, value, fill = variable, color = variable)) +
  geom_col(position = "dodge2") + 
  geom_text(aes( label = value, y = value + 10), position = position_dodge(0.9), color = "black") + 
  scale_color_manual(name = "", values = c("grey", "red", "blue"))  +
  scale_fill_manual(name = "", values = c("grey", "red", "blue")) + 
  labs(y = "Number of variant proteins", x = "Comparison") + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, color = "black", hjust = 1, vjust = 0.5),
        axis.text.y = element_text(color = "black"))

```

To do the boxplot of the data before normalization, I got the normalization factors from page 3 of the report as I do not have the actual data before normalization. However, as the data was re-analysed, maybe those are not the right normalization factors.

Sample | Normalization factors
:-:|:-:
CTRL1 | 1.13
CTRL2 | 0.96
CTRL3 |1.05
IFN1 | 1.01
IFN2 | 0.97
IFN3 | 0.95
VI1 | 1.08
VI2 | 0.97
VI3 | 1.01
NL1 | 1
NL2 | 1
NL3 | 1

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
normalized_abundances <- read.delim("normalized_abundances.txt", header = T, stringsAsFactors = F)
normalized_abundances$gene_name <- gsub(".*GN=(\\w+).*", "\\1", normalized_abundances$Description)
norm_abundances <- data.frame(normalized_abundances[,3:14] %>% log2(), 
                              row.names = normalized_abundances$Accession)

plot_boxplot <- melt(norm_abundances)
plot_boxplot$Test <- plot_boxplot$variable <- as.character(plot_boxplot$variable)

for (i in 1:nrow(plot_boxplot)) {
  if (grepl("CTRL", plot_boxplot$Test[i])) {
    plot_boxplot$Test[i] = "Control"
  } else if (grepl("^IFN\\d$", plot_boxplot$Test[i])) {
    plot_boxplot$Test[i] = "IFN"
  } else if (grepl("^VIRUS\\d$", plot_boxplot$Test[i])) {
    plot_boxplot$Test[i] = "NL"
    plot_boxplot$variable[i] = gsub("VIRUS", "NL", plot_boxplot$variable[i])
  } else {
    plot_boxplot$Test[i] = "VI"
    plot_boxplot$variable[i] = gsub("IFN_VIRUS", "VI", plot_boxplot$variable[i])
  }
}
plot_boxplot$Normalization <- "After Normalization"

```


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
normalization_factors <- c(
  "CTRL1" = 1.13, "CTRL2" = 0.96, "CTRL3" = 1.05, 
  "IFN1" = 1.01, "IFN2" = 0.97, "IFN3" = 0.95, 
  "VI1" = 1.08, "VI2" = 0.97, "VI3" = 1.01, 
  "NL1" = 1, "NL2" = 1, "NL3" = 1)

org_abundances <- data.frame(0,0)

for (i in names(normalization_factors)) { 
  if (grepl("VI", i)) { 
    a <- gsub("VI", "IFN_VIRUS", i)
    org_abundances <- data.frame(cbind(org_abundances, (normalized_abundances[, a] * normalization_factors[i]) %>% log2()))
    colnames(org_abundances)[ncol(org_abundances)] <- a
    
  } else if (grepl("NL", i)) { 
    a <- gsub("NL", "VIRUS", i) 
    org_abundances <- data.frame(cbind(org_abundances, (normalized_abundances[, a] * normalization_factors[i]) %>% log2()))
    colnames(org_abundances)[ncol(org_abundances)] <- a
  } else {
    org_abundances <- data.frame(cbind(org_abundances, (normalized_abundances[, i] * normalization_factors[i]) %>% log2()))
    colnames(org_abundances)[ncol(org_abundances)] <- i
  }
}
org_abundances$X0 <- org_abundances$X0.1 <- NULL

rownames(org_abundances) <- normalized_abundances$Accession
```


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
plot_boxplot_org <- melt(org_abundances)
plot_boxplot_org$Test <- plot_boxplot_org$variable <- as.character(plot_boxplot_org$variable)

for (i in 1:nrow(plot_boxplot_org)) {
  if (grepl("CTRL", plot_boxplot_org$Test[i])) {
    plot_boxplot_org$Test[i] = "Control"
  } else if (grepl("^IFN\\d$", plot_boxplot_org$Test[i])) {
    plot_boxplot_org$Test[i] = "IFN"
  } else if (grepl("^VIRUS\\d$", plot_boxplot_org$Test[i])) {
    plot_boxplot_org$Test[i] = "NL"
    plot_boxplot_org$variable[i] = gsub("VIRUS", "NL", plot_boxplot_org$variable[i])
  } else {
    plot_boxplot_org$Test[i] = "VI"
    plot_boxplot_org$variable[i] = gsub("IFN_VIRUS", "VI", plot_boxplot_org$variable[i])
  }
}
plot_boxplot_org$Normalization <- "Before Normalization"
```

```{r echo=FALSE, fig.height=6, fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
plot_boxplot_org$variable <- factor(plot_boxplot_org$variable, 
                                levels = c(paste0("CTRL", 1:3), paste0("IFN", 1:3),
                                           paste0("VI", 1:3), paste0("NL", 1:3)))
plot_boxplot_org$Test <- factor(plot_boxplot_org$Test, levels = c("Control", "IFN", "VI", "NL"))

joined_plots <- rbind(plot_boxplot, plot_boxplot_org)
joined_plots$Normalization <- factor(joined_plots$Normalization, 
                                     levels = c("Before Normalization", "After Normalization"))

ggplot(joined_plots, aes(variable, value, fill = Test)) + 
  geom_boxplot() + scale_fill_manual(values = c("#db8823", "#106909", "#8f2424", "#1082b3")) +
  labs(x = "", y = expression(log[2](Intensity))) +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, color = "black", hjust = 1, vjust = 0.5),
        legend.position = "none") + 
  facet_wrap(~Normalization, nrow = 1)

```

```{r echo=FALSE, fig.height=10, fig.width=6, message=FALSE, warning=FALSE, paged.print=FALSE}

ggplot(joined_plots, aes(variable, value, fill = Test)) + 
  geom_boxplot() + scale_fill_manual(values = c("#db8823", "#106909", "#8f2424", "#1082b3")) +
  labs(x = "", y = expression(log[2](Intensity))) +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, color = "black", hjust = 1, vjust = 0.5),
        legend.position = "none") + 
  facet_wrap(~Normalization, nrow = 2)

```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
pca_data <- data.frame(Replicate = plot_boxplot$variable %>% unique(),
                       Sample = gsub("(\\w+)\\d", "\\1", plot_boxplot$variable %>% unique()),
                       PC1 = c(32.8, 34.8, 47, 25.9, 28, 46, -52, 0.5, 10.3, -68, -59, -44),
                       PC2 = c(28, 22, -9.9, -9, -36, -42, 15.7, 13.8, 56.5, -14.8, -10.1, -14))

ggplot(pca_data, aes(PC1, PC2, color = Sample, label = Replicate)) + 
  labs(x = "PC1: 38.1% expl. variation", y = "PC2: 15.4% expl. variation") + 
  scale_color_manual(values = c("#1082b3", "#db8823", "grey3", "#106909")) + 
  geom_hline(yintercept = 0, linetype = 2, alpha = 0.5) + 
  geom_vline(xintercept = 0, linetype = 2, alpha = 0.5) +
  geom_label() +
  scale_x_continuous(breaks = seq(-75, 50, 12.5)) + 
  theme_bw() + theme(legend.position = "none",
                     axis.text = element_text(color = "black"))
```

```{r echo=FALSE, fig.height=10, fig.width=7, message=FALSE, warning=FALSE, paged.print=FALSE}
library(ComplexHeatmap)
mean <- apply(norm_abundances, 1, mean)
stdev <- apply(norm_abundances, 1, sd)

heatmap_data <- data.frame(cbind((norm_abundances - mean) / stdev, Accession = normalized_abundances$Accession))
colnames(heatmap_data)[1:12] <- plot_boxplot$variable %>% unique()

dend_samples <- as.matrix(norm_abundances) %>% t() %>% dist() %>% hclust() 
order_samples <- dend_samples$order

dend_prots <- as.matrix(norm_abundances) %>% dist() %>% hclust() 
order_prots <- dend_prots$order

Heatmap(heatmap_data[, -13], name = "Zscore ratio", column_names_side = "top",
        cluster_rows =  dend_prots, cluster_columns = dend_samples,
        row_labels = rep("", nrow(heatmap_data)),
        column_title = "Dendrogram calculated with Zscore",
        row_title = "Dendrogram calculated with Zscore",
        show_row_dend = F)

Heatmap(heatmap_data[, -13], name = "Zscore ratio", column_names_side = "top",
        row_labels = rep("", nrow(heatmap_data)), cluster_rows = T, show_row_dend = F,
        column_title = "Dendrogram calculated with normalized abundances",
        row_title = "Dendrogram calculated with normalized abundances")
```


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
Tests <- for_plots
Tests$Status <-  as.character(Tests$Status)
for (prot in 1:nrow(Tests)) {
    
    if (Tests$Status[prot] == "VARIANT") {
      
      if (Tests$Zscore_ratio[prot] > 1.96 ) {
        Tests$Status[prot] <- "Down-regulated"
      } else if (Tests$Zscore_ratio[prot] < -1.96) {
        Tests$Status[prot] <- "Up-regulated"
      } else {
        Tests$Status[prot] <- FALSE
      }
      
    } else if (!is.na(Tests$qValue[prot]) & Tests$qValue[prot] < 0.05) {
      
      if (Tests$Zscore_ratio[prot] > 1.96 ) {
        Tests$Status[prot] <- "Down-regulated"
      } else if (Tests$Zscore_ratio[prot] < -1.96) {
        Tests$Status[prot] <- "Up-regulated"
      } else {
        Tests$Status[prot] <- FALSE
      }
      
    } else {
      Tests$Status[prot] <- FALSE
    }
}
```


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
volcanos <- 
  ggplot(Tests, aes(-1*Zscore_ratio, -log10(qValue), color = Status, label = Accession)) + 
  geom_point() + #geom_text(data = Tests %>% filter(Status != FALSE ), check_overlap = T) + 
  scale_color_manual(values = c("blue", "grey", "red")) + 
  labs(x = expression(log[2]("Z-Score Ratio")), y = expression(-log[10](qValue))) + 
  theme_bw() + theme(legend.position = "none") + 
  facet_wrap(~Test, nrow = 3 )

```

```{r fig.height=10, fig.width=8, message=FALSE, warning=FALSE, paged.print=FALSE}
volcanos
```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(ensembldb)
library(EnsDb.Hsapiens.v86)
edb <- EnsDb.Hsapiens.v86::EnsDb.Hsapiens.v86

txs <- transcripts(edb, columns = c("gene_name", "uniprot_id"))@elementMetadata@listData %>%
  as.data.frame() %>% dplyr::select(uniprot_id, gene_name) 

txs <- dplyr::filter(txs, !is.na(uniprot_id) & !is.na(gene_name))

gene_names <- data.frame(0, 0)
for (i in org.adj.pVal$Accession) { 
  if (i %in% gene_names$X0) {next}
  gene_names <- rbind(gene_names, c(X0 = i, X0.1 = as.character(txs$gene_name[txs$uniprot_id == i][1])))
}

gene_names <- gene_names[-1,]
colnames(gene_names) <- colnames(txs)
```

```{r echo=FALSE, fig.height=4, fig.width=7, message=FALSE, warning=FALSE, paged.print=FALSE}

vplots_data <- list()

for (i in unique(Tests$Test)) {
  vplots_data[[i]] <- dplyr::filter(Tests, Test == i) %>% cbind(gene_name = gene_names$gene_name)
  print(
    ggplot(vplots_data[[i]], aes(-1*Zscore_ratio, -log10(qValue), color = Status, label = gene_name)) + 
      geom_point(size = 1) + 
      geom_text(data = vplots_data[[i]] %>% dplyr::filter(Status != FALSE ), 
                nudge_y = 0.5, check_overlap = T, size = 3) + 
      scale_color_manual(values = c("blue", "grey", "red")) + 
      #scale_x_continuous(limits = c(-10, 12), breaks = c(seq(-10, 12, 4), 0)) + 
      scale_y_continuous(breaks = seq(0, 15, 2.5)) + 
      labs(x = expression(log[2]("Z-Score Ratio")), y = expression(-log[10](qValue)), title = i) + 
      theme_bw() + theme(legend.position = "none") 
    
  )
}
```

```{r echo=FALSE, fig.height=12, fig.width=4, message=FALSE, warning=FALSE, paged.print=FALSE}
heatmap_dt <- data.frame(heatmap_data, gene_names)
heatmap_dt <- heatmap_dt[, !colnames(heatmap_dt) %in% c("Accession", "uniprot_id")]

deregs <- samples <- data <- dereg_heatmaps <- name <- list()
for (i in levels(Tests$Test)) {
  if (i %in% c("IFN vs Control", "NL vs Control")) {
    deregs[[i]] <- Tests$Accession[Tests$Test == i & Tests$Status %in% c("Up-regulated", "Down-regulated")]
    name[[i]] <- heatmap_dt$gene_name[rownames(heatmap_dt) %in% deregs[[i]]]
    
    for (prot in 1:length(name[[i]])) {
      name[[i]][prot] <- ifelse(is.na(name[[i]][prot]),
                                deregs[[i]][prot],
                                name[[i]][prot])
    }
    
    samples[[i]] <- sort(paste0(strsplit(i, split = " vs ")[[1]], rep(1:3, 2)))
    samples[[i]] <- gsub("Control", "CTRL", samples[[i]])
    data[[i]] <- heatmap_dt[deregs[[i]], samples[[i]]]
    dereg_heatmaps[[i]] <- Heatmap(data[[i]], row_names_gp = gpar(fontsize = 6),
                                   column_title = i, 
                                   column_names_gp = gpar(fontsize = 9),
                                   column_dend_height = unit(2.5, "mm"),
                                   column_names_side = "top", row_names_side = "left",
                                   row_labels = name[[i]], name = "log2(Intensity)"
                                   )
  }
}

dereg_heatmaps[[1]]
dereg_heatmaps[[2]]
```

